In [1]:
from algorithm.utils.data.tf.dataimage import DataImage
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf
import keras
%load_ext tensorboard

In [2]:
dataset = DataImage(data_path="Input/dataset", split=0.2, resize=True, height='auto', width='auto', normalize=True, mean='auto', name="Electronic components dataset", batch_size=16)

In [3]:
dataset

Electronic components dataset
	Number of points: 1223
	Root location: Input/dataset
	Split: 0.2
	Transform used:	Resize(size=(128, 128)
	Normalize(mean=[0.00392156862745098, 0.00392156862745098, 0.00392156862745098], std=None)


In [4]:
trainset = dataset.get_set(split="train")
validset = dataset.get_set(split="validation")

In [5]:
# get some random training images
dataiter = iter(trainset)
images, labels = next(dataiter)

In [6]:
images.shape, len(labels)

(TensorShape([16, 128, 128, 3]), 16)

In [7]:
images

<tf.Tensor: shape=(16, 128, 128, 3), dtype=float32, numpy=
array([[[[0.62784666, 0.6003957 , 0.38863096],
         [0.6233758 , 0.5959248 , 0.38416007],
         [0.6527421 , 0.6252911 , 0.4135264 ],
         ...,
         [0.0891829 , 0.13624172, 0.08133976],
         [0.10305631, 0.15011513, 0.09521317],
         [0.09884848, 0.1459073 , 0.09100534]],

        [[0.22205046, 0.26256034, 0.19946195],
         [0.57070243, 0.56023145, 0.36039013],
         [0.74955004, 0.70303386, 0.42435497],
         ...,
         [0.0937871 , 0.14084592, 0.09017191],
         [0.1009038 , 0.14796263, 0.09728861],
         [0.10301778, 0.1500766 , 0.09940258]],

        [[0.11720498, 0.1910671 , 0.10631774],
         [0.11357638, 0.15598959, 0.12430827],
         [0.13477951, 0.14888175, 0.11939339],
         ...,
         [0.10588236, 0.15294118, 0.09803922],
         [0.10588236, 0.15294118, 0.09803922],
         [0.09803922, 0.14509805, 0.09019608]],

        ...,

        [[0.13880424, 0.14840902,

In [8]:
labels

<tf.Tensor: shape=(16,), dtype=string, numpy=
array([b'SO16', b'RESISTOR', b'CAPACITOR', b'PINSMD', b'PINSMD',
       b'PINSMD', b'C1210', b'PINTH', b'CAPACITOR', b'0805S', b'SO8',
       b'PINSMD', b'PINTH', b'PINTH', b'R63H40', b'CAPACITOR'],
      dtype=object)>

In [9]:
class_names = dataset.labels

In [10]:
class_names

['R0603',
 'RELAIS',
 'MINIMELF',
 'STRIP6',
 'R0805',
 'JUMPER',
 'VOLTAGEREGULATOR',
 'R01005',
 'R20',
 'WSK2512',
 '0805S',
 'C0603',
 'AUTIC',
 'PLCC2LED',
 'LED3',
 'SO16',
 'X18Y4',
 'INDUCTANCE',
 'RESISTOR',
 'FUSE',
 'PINSMD',
 'TRIAC',
 'SFUSE',
 'SMB',
 'S5SOT23',
 'C0805',
 'CAPACITOR',
 'X63H40',
 'R63H40',
 'PINTH',
 'OPENFIX',
 'DIODE',
 'C1210',
 'CASEC',
 'X4Y18',
 'LED',
 'STRIP3',
 'CTELRJ45',
 'R110H126',
 'SO8',
 'MOS',
 'X43Y55',
 'R1206',
 'R0402',
 'ZENER',
 'SCR',
 'X50Y65',
 'X8Y11',
 'DIGITAL',
 'GATE',
 'OSCILLATOR',
 'R2512',
 'TRANSISTOR',
 'R10',
 'OPTOISOLATOR',
 'TRANSFORMER',
 'CONNECTOR']

In [ ]:
import matplotlib.pyplot as plt
image_batch, label_batch = next(iter(trainset))

plt.figure(figsize=(60, 60))
for i in range(9):
    ax = plt.subplot(3, 3, i + 1)
    plt.imshow(image_batch[i].numpy().astype("uint8")) # to be implemented: normalization and resize
    label = label_batch[i].numpy().decode("utf-8")
    plt.title(label, fontsize=60)
    plt.axis("off")

In [12]:
from algorithm.deep.tf.neural_networks import ResNet2__1

In [13]:
trainset = dataset.apply_one_hot_encoding(trainset)
validset = dataset.apply_one_hot_encoding(validset)

In [14]:
out_dir = "out/models/ResNet2__1"

In [15]:
model = ResNet2__1(len(class_names),input_shape=(128, 128, 3))
tb_callback = keras.callbacks.TensorBoard(log_dir=f'{out_dir}/tensorboard_log', histogram_freq=1)

In [16]:
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss=keras.losses.categorical_crossentropy,
    metrics=["accuracy"],
    run_eagerly=True,
)

In [17]:
model.fit(trainset, validation_data=validset, epochs=1000, callbacks=[tb_callback])

Epoch 1/1000
62/62 [==============================] - 29s 425ms/step - loss: 2.1503 - accuracy: 0.5383 - val_loss: 1.7246 - val_accuracy: 0.5902
Epoch 2/1000
62/62 [==============================] - 23s 371ms/step - loss: 1.2712 - accuracy: 0.6701 - val_loss: 1.7020 - val_accuracy: 0.5861
Epoch 3/1000
62/62 [==============================] - 23s 374ms/step - loss: 1.0815 - accuracy: 0.7038 - val_loss: 1.6541 - val_accuracy: 0.6270
Epoch 4/1000
62/62 [==============================] - 24s 378ms/step - loss: 0.8955 - accuracy: 0.7324 - val_loss: 1.4958 - val_accuracy: 0.5984
Epoch 5/1000
62/62 [==============================] - 25s 396ms/step - loss: 0.8367 - accuracy: 0.7344 - val_loss: 1.6374 - val_accuracy: 0.6230
Epoch 6/1000
62/62 [==============================] - 26s 413ms/step - loss: 0.7136 - accuracy: 0.7783 - val_loss: 1.6587 - val_accuracy: 0.6066
Epoch 7/1000
62/62 [==============================] - 24s 381ms/step - loss: 0.7066 - accuracy: 0.7712 - val_loss: 1.6002 - val_ac

In [22]:
model.summary()

Model: "res_net2__1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 resnet152 (Functional)      (None, 4, 4, 2048)        58370944  
                                                                 
 flatten (Flatten)           (None, 32768)             0         
                                                                 
 dense (Dense)               (None, 1000)              32769000  
                                                                 
 dense_1 (Dense)             (None, 57)                57057     
                                                                 
 model (Functional)          (None, 57)                91197001  
                                                                 
Total params: 91197001 (347.89 MB)
Trainable params: 32826057 (125.22 MB)
Non-trainable params: 58370944 (222.67 MB)
_________________________________________________________________


In [19]:
model.save(out_dir)

INFO:tensorflow:Assets written to: out/models/ResNet2__1/assets


INFO:tensorflow:Assets written to: out/models/ResNet2__1/assets


In [ ]:
keras.utils.plot_model(model, f'{out_dir}/ResNet2__1.svg', show_shapes=True, show_layer_activations=True, show_layer_names=True)

In [21]:
# Evaluation on unseen data.

test_loss, test_acc = model.evaluate(validset, verbose=2)
print('\nTest accuracy:', test_acc)

16/16 - 2s - loss: 6.8737 - accuracy: 0.6189 - 2s/epoch - 140ms/step

Test accuracy: 0.618852436542511
