In [1]:
from algorithm.utils.data.tf.dataimage import DataImage
import tensorflow as tf
import keras
%load_ext tensorboard

In [2]:
dataset = DataImage(data_path="Input/dataset", split=0.2, resize=True, height='auto', width='auto', normalize=True, mean='auto', name="Electronic components dataset", batch_size=16)

In [3]:
dataset

Electronic components dataset
	Number of points: 1223
	Root location: Input/dataset
	Split: 0.2
	Transform used:	Resize(size=(128, 128)
	Normalize(mean=[0.00392156862745098, 0.00392156862745098, 0.00392156862745098], std=None)


In [4]:
trainset = dataset.get_set(split="train")
validset = dataset.get_set(split="validation")

In [5]:
# get some random training images
dataiter = iter(trainset)
images, labels = next(dataiter)

In [6]:
images.shape, len(labels)

(TensorShape([16, 128, 128, 3]), 16)

In [7]:
images

<tf.Tensor: shape=(16, 128, 128, 3), dtype=float32, numpy=
array([[[[0.10588236, 0.15294118, 0.09803922],
         [0.10588236, 0.15294118, 0.09803922],
         [0.10588236, 0.15294118, 0.09803922],
         ...,
         [0.15673302, 0.211635  , 0.12143891],
         [0.14712441, 0.20202638, 0.11183029],
         [0.13552535, 0.1904273 , 0.10023122]],

        [[0.10588236, 0.15294118, 0.09803922],
         [0.10588236, 0.15294118, 0.09803922],
         [0.10588236, 0.15294118, 0.09803922],
         ...,
         [0.14820772, 0.2031097 , 0.11291361],
         [0.13624628, 0.19114824, 0.10095216],
         [0.12740934, 0.18231131, 0.09211522]],

        [[0.10358457, 0.15179229, 0.09229474],
         [0.10448214, 0.15268986, 0.09319231],
         [0.10699535, 0.15520307, 0.09570552],
         ...,
         [0.14607365, 0.20097561, 0.11077953],
         [0.13621324, 0.1911152 , 0.10091912],
         [0.12454858, 0.17945056, 0.08925447]],

        ...,

        [[0.1137255 , 0.16078432,

In [8]:
labels

<tf.Tensor: shape=(16,), dtype=string, numpy=
array([b'RESISTOR', b'PINTH', b'CAPACITOR', b'RESISTOR', b'CAPACITOR',
       b'PINSMD', b'R20', b'R20', b'R0805', b'PINTH', b'PINTH',
       b'CAPACITOR', b'SFUSE', b'PINTH', b'CAPACITOR', b'DIODE'],
      dtype=object)>

In [9]:
class_names = dataset.labels

In [10]:
class_names

['INDUCTANCE',
 'OPTOISOLATOR',
 'GATE',
 'PLCC2LED',
 'R10',
 'R2512',
 'ZENER',
 'S5SOT23',
 'C0805',
 '0805S',
 'X43Y55',
 'X18Y4',
 'X8Y11',
 'OPENFIX',
 'SCR',
 'JUMPER',
 'R0805',
 'SO8',
 'CTELRJ45',
 'FUSE',
 'CAPACITOR',
 'DIGITAL',
 'AUTIC',
 'OSCILLATOR',
 'TRIAC',
 'CONNECTOR',
 'LED3',
 'R0402',
 'SO16',
 'R1206',
 'RESISTOR',
 'RELAIS',
 'LED',
 'MINIMELF',
 'X63H40',
 'STRIP3',
 'R0603',
 'DIODE',
 'SFUSE',
 'C0603',
 'TRANSFORMER',
 'SMB',
 'PINTH',
 'MOS',
 'VOLTAGEREGULATOR',
 'X50Y65',
 'R01005',
 'TRANSISTOR',
 'CASEC',
 'R20',
 'WSK2512',
 'X4Y18',
 'STRIP6',
 'R63H40',
 'R110H126',
 'PINSMD',
 'C1210']

In [ ]:
import matplotlib.pyplot as plt
image_batch, label_batch = next(iter(trainset))

plt.figure(figsize=(60, 60))
for i in range(9):
    ax = plt.subplot(3, 3, i + 1)
    plt.imshow(image_batch[i].numpy().astype("uint8")) # to be implemented: normalization and resize
    label = label_batch[i].numpy().decode("utf-8")
    plt.title(label, fontsize=60)
    plt.axis("off")

In [12]:
from algorithm.deep.tf.neural_networks import ResNet1

In [13]:
trainset = dataset.apply_one_hot_encoding(trainset)
validset = dataset.apply_one_hot_encoding(validset)

In [14]:
out_dir = "out\models\ResNet1_1"

In [15]:
model = ResNet1(len(class_names),input_shape=(128, 128, 3))
tb_callback = keras.callbacks.TensorBoard(log_dir=f'{out_dir}/tensorboard_log', histogram_freq=1)

In [16]:
model.compile(
    optimizer=keras.optimizers.RMSprop(1e-3),
    loss=keras.losses.CategoricalCrossentropy(from_logits=True),
    metrics=["accuracy"],
    run_eagerly=True,
)

In [17]:
model.fit(trainset, validation_data=validset, epochs=1000, callbacks=[tb_callback])

Epoch 1/1000
62/62 [==============================] - 42s 668ms/step - loss: 3.1645 - accuracy: 0.1798 - val_loss: 2.7714 - val_accuracy: 0.1885
Epoch 2/1000
62/62 [==============================] - 41s 663ms/step - loss: 2.7135 - accuracy: 0.2022 - val_loss: 2.7307 - val_accuracy: 0.2623
Epoch 3/1000
62/62 [==============================] - 41s 661ms/step - loss: 2.4924 - accuracy: 0.2993 - val_loss: 2.6514 - val_accuracy: 0.2869
Epoch 4/1000
62/62 [==============================] - 41s 660ms/step - loss: 2.3643 - accuracy: 0.3544 - val_loss: 2.5070 - val_accuracy: 0.3852
Epoch 5/1000
62/62 [==============================] - 41s 663ms/step - loss: 2.2190 - accuracy: 0.3749 - val_loss: 2.2397 - val_accuracy: 0.4549
Epoch 6/1000
62/62 [==============================] - 42s 673ms/step - loss: 2.0768 - accuracy: 0.4351 - val_loss: 2.1068 - val_accuracy: 0.4098
Epoch 7/1000
62/62 [==============================] - 41s 666ms/step - loss: 1.9889 - accuracy: 0.4474 - val_loss: 2.1144 - val_ac

In [18]:
model.save(out_dir)

INFO:tensorflow:Assets written to: out\models\ResNet1_1\assets


INFO:tensorflow:Assets written to: out\models\ResNet1_1\assets


In [19]:
model.summary()

Model: "res_net1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             multiple                  896       
                                                                 
 conv2d_1 (Conv2D)           multiple                  18496     
                                                                 
 max_pooling2d (MaxPooling2  multiple                  0         
 D)                                                              
                                                                 
 res_net_block (ResNetBlock  multiple                  73856     
 )                                                               
                                                                 
 res_net_block_1 (ResNetBlo  multiple                  73856     
 ck)                                                             
                                                          

In [26]:
keras.utils.plot_model(model, f'{out_dir}/ResNet1.png', show_shapes=True)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.


In [24]:
# Evaluation on unseen data.

test_loss, test_acc = model.evaluate(validset, verbose=2)
print('\nTest accuracy:', test_acc)

16/16 - 3s - loss: 3.0212 - accuracy: 0.1885 - 3s/epoch - 188ms/step

Test accuracy: 0.18852458894252777
