In [12]:
from algorithm.utils.data.tf.dataimage import DataImage
import tensorflow as tf
import os

In [13]:
dataset = DataImage(data_path="Input/dataset", split=0.2, resize=True, height='auto', width='auto', name="Electronic components dataset", batch_size=16)

In [14]:
dataset

Electronic components dataset
	Number of points: 1223
	Root location: Input/dataset
	Split: 0.2
	Transform used:	Resize(size=(128, 128)


In [25]:
trainset = dataset.get_set(split="train")
validset = dataset.get_set(split="validation")

In [26]:
# get some random training images
dataiter = iter(trainset)
images, labels = next(dataiter)

In [27]:
images.shape, len(labels)

(TensorShape([16, 128, 128, 3]), 16)

In [28]:
images

<tf.Tensor: shape=(16, 128, 128, 3), dtype=float32, numpy=
array([[[[ 15.      ,  35.      ,  23.      ],
         [ 15.      ,  35.      ,  23.      ],
         [ 15.      ,  35.      ,  23.      ],
         ...,
         [ 15.      ,  35.      ,  23.      ],
         [ 15.      ,  35.      ,  23.      ],
         [ 15.      ,  35.      ,  23.      ]],

        [[ 15.      ,  35.      ,  23.      ],
         [ 15.      ,  35.      ,  23.      ],
         [ 15.      ,  35.      ,  23.      ],
         ...,
         [ 15.      ,  35.      ,  23.      ],
         [ 15.      ,  35.      ,  23.      ],
         [ 15.      ,  35.      ,  23.      ]],

        [[ 15.      ,  35.      ,  23.      ],
         [ 15.      ,  35.      ,  23.      ],
         [ 15.      ,  35.      ,  23.      ],
         ...,
         [ 15.      ,  35.      ,  23.      ],
         [ 15.      ,  35.      ,  23.      ],
         [ 15.      ,  35.      ,  23.      ]],

        ...,

        [[ 17.      ,  37.      ,

In [29]:
labels

<tf.Tensor: shape=(16,), dtype=string, numpy=
array([b'PINSMD', b'RESISTOR', b'0805S', b'0805S', b'CONNECTOR', b'PINTH',
       b'RESISTOR', b'R20', b'CAPACITOR', b'R01005', b'CAPACITOR',
       b'RESISTOR', b'CAPACITOR', b'DIODE', b'RESISTOR', b'CAPACITOR'],
      dtype=object)>